module.exports = [
  {
    groupId: 'g1',
    name: 'قهرمانان دانش',
    score: 22100,
    members: 23,
    admin: 'علی رضایی',
    created: '۱۴۰۲/۰۲/۱۵',
    wins: 58,
    losses: 14,
    memberList: ['علی رضایی', 'سارا اکبری', 'رضا کریمی', 'ندا فرهمند', 'پیام سالاری'],
    matches: [
      { opponentId: 'g2', opponent: 'متفکران جوان', time: '۱۴۰۳/۰۵/۲۵ ۱۸:۰۰' },
    ],
    requests: [],
    roster: [
      { name: 'علی رضایی', avatar: 'https://i.pravatar.cc/100?img=12', role: 'رهبر تیم', power: 94, avgScore: 890, accuracy: 92, speed: 6.1 },
      { name: 'سارا اکبری', avatar: 'https://i.pravatar.cc/100?img=32', role: 'استاد ادبیات', power: 91, avgScore: 872, accuracy: 90, speed: 6.4 },
      { name: 'رضا کریمی', avatar: 'https://i.pravatar.cc/100?img=45', role: 'تحلیل‌گر تیزبین', power: 89, avgScore: 860, accuracy: 89, speed: 6.6 },
      { name: 'ندا فرهمند', avatar: 'https://i.pravatar.cc/100?img=36', role: 'متخصص تاریخ', power: 87, avgScore: 845, accuracy: 88, speed: 6.9 },
      { name: 'پیام سالاری', avatar: 'https://i.pravatar.cc/100?img=24', role: 'ریاضی برتر', power: 85, avgScore: 832, accuracy: 87, speed: 7.1 },
      { name: 'آرزو مرادی', avatar: 'https://i.pravatar.cc/100?img=54', role: 'هوش کلامی', power: 83, avgScore: 820, accuracy: 85, speed: 7.4 },
      { name: 'احسان کاوه', avatar: 'https://i.pravatar.cc/100?img=13', role: 'مغز تکنولوژی', power: 82, avgScore: 808, accuracy: 84, speed: 7.6 },
      { name: 'نگار میرزایی', avatar: 'https://i.pravatar.cc/100?img=47', role: 'دانش عمومی', power: 80, avgScore: 798, accuracy: 83, speed: 7.8 },
      { name: 'شهاب احمدپور', avatar: 'https://i.pravatar.cc/100?img=58', role: 'فیزیک‌دان جوان', power: 78, avgScore: 785, accuracy: 81, speed: 8 },
      { name: 'کیانا شریفی', avatar: 'https://i.pravatar.cc/100?img=21', role: 'تحلیل‌گر داده', power: 76, avgScore: 770, accuracy: 80, speed: 8.2 },
    ],
  },
  {
    groupId: 'g2',
    name: 'متفکران جوان',
    score: 19800,
    members: 18,
    admin: 'سارا محمدی',
    created: '۱۴۰۲/۰۳/۲۰',
    wins: 46,
    losses: 21,
    memberList: ['سارا محمدی', 'مهدی احمدی', 'الهام برزگر', 'حسین فلاح'],
    matches: [
      { opponentId: 'g5', opponent: 'پیشروان علم', time: '۱۴۰۳/۰۵/۳۰ ۱۹:۰۰' },
    ],
    requests: [],
    roster: [
      { name: 'سارا محمدی', avatar: 'https://i.pravatar.cc/100?img=29', role: 'استراتژیست ارشد', power: 92, avgScore: 875, accuracy: 91, speed: 6.3 },
      { name: 'مهدی احمدی', avatar: 'https://i.pravatar.cc/100?img=17', role: 'تحلیل‌گر منطق', power: 88, avgScore: 852, accuracy: 88, speed: 6.7 },
      { name: 'الهام برزگر', avatar: 'https://i.pravatar.cc/100?img=53', role: 'متخصص علوم', power: 86, avgScore: 838, accuracy: 87, speed: 7 },
      { name: 'حسین فلاح', avatar: 'https://i.pravatar.cc/100?img=25', role: 'ریاضی‌دان تیم', power: 84, avgScore: 826, accuracy: 85, speed: 7.3 },
      { name: 'نگین شریعتی', avatar: 'https://i.pravatar.cc/100?img=41', role: 'هوش تاریخی', power: 83, avgScore: 815, accuracy: 84, speed: 7.5 },
      { name: 'پژمان نظری', avatar: 'https://i.pravatar.cc/100?img=34', role: 'کارشناس فناوری', power: 81, avgScore: 804, accuracy: 83, speed: 7.8 },
      { name: 'بهاره کاظمی', avatar: 'https://i.pravatar.cc/100?img=59', role: 'ادبیات پژوه', power: 79, avgScore: 792, accuracy: 82, speed: 8 },
      { name: 'شروین فرهادی', avatar: 'https://i.pravatar.cc/100?img=23', role: 'هوش مصنوعی', power: 78, avgScore: 780, accuracy: 81, speed: 8.2 },
      { name: 'مینا رستگار', avatar: 'https://i.pravatar.cc/100?img=42', role: 'دانش عمومی', power: 76, avgScore: 768, accuracy: 80, speed: 8.4 },
      { name: 'آرین ساعی', avatar: 'https://i.pravatar.cc/100?img=14', role: 'حل مسئله سریع', power: 75, avgScore: 756, accuracy: 79, speed: 8.6 },
    ],
  },
  {
    groupId: 'g3',
    name: 'چالش‌برانگیزان',
    score: 20500,
    members: 21,
    admin: 'رضا قاسمی',
    created: '۱۴۰۲/۰۱/۱۰',
    wins: 50,
    losses: 18,
    memberList: ['رضا قاسمی', 'نازنین فراهانی', 'کیاوش نادری'],
    matches: [],
    requests: [],
    roster: [
      { name: 'رضا قاسمی', avatar: 'https://i.pravatar.cc/100?img=19', role: 'رهبر خلاق', power: 90, avgScore: 862, accuracy: 89, speed: 6.5 },
      { name: 'نازنین فراهانی', avatar: 'https://i.pravatar.cc/100?img=38', role: 'محقق علوم', power: 87, avgScore: 840, accuracy: 87, speed: 6.9 },
      { name: 'کیاوش نادری', avatar: 'https://i.pravatar.cc/100?img=49', role: 'استاد منطق', power: 85, avgScore: 828, accuracy: 85, speed: 7.2 },
      { name: 'الینا رضوی', avatar: 'https://i.pravatar.cc/100?img=28', role: 'تحلیل‌گر داده', power: 83, avgScore: 815, accuracy: 84, speed: 7.4 },
      { name: 'پارسا بهمنی', avatar: 'https://i.pravatar.cc/100?img=33', role: 'هوش ریاضی', power: 82, avgScore: 804, accuracy: 83, speed: 7.6 },
      { name: 'آیدا صفوی', avatar: 'https://i.pravatar.cc/100?img=52', role: 'تاریخ‌دان', power: 80, avgScore: 792, accuracy: 82, speed: 7.9 },
      { name: 'مانی فرهودی', avatar: 'https://i.pravatar.cc/100?img=22', role: 'متخصص سرعت', power: 79, avgScore: 780, accuracy: 81, speed: 8 },
      { name: 'سینا کیا', avatar: 'https://i.pravatar.cc/100?img=27', role: 'کارشناس فناوری', power: 77, avgScore: 770, accuracy: 80, speed: 8.2 },
      { name: 'هستی مرادی', avatar: 'https://i.pravatar.cc/100?img=44', role: 'دانش عمومی', power: 75, avgScore: 760, accuracy: 79, speed: 8.4 },
      { name: 'یاشا طاهری', avatar: 'https://i.pravatar.cc/100?img=57', role: 'حل مسئله منطقی', power: 74, avgScore: 748, accuracy: 78, speed: 8.6 },
    ],
  },
  {
    groupId: 'g4',
    name: 'دانش‌آموزان نخبه',
    score: 18700,
    members: 15,
    admin: 'مریم احمدی',
    created: '۱۴۰۲/۰۴/۰۵',
    wins: 33,
    losses: 27,
    memberList: ['مریم احمدی', 'رها فاضلی', 'امیررضا حاتمی'],
    matches: [],
    requests: [],
    roster: [
      { name: 'مریم احمدی', avatar: 'https://i.pravatar.cc/100?img=18', role: 'رهبر تکنیکی', power: 89, avgScore: 850, accuracy: 88, speed: 6.8 },
      { name: 'رها فاضلی', avatar: 'https://i.pravatar.cc/100?img=48', role: 'هوش ادبی', power: 86, avgScore: 832, accuracy: 86, speed: 7.1 },
      { name: 'امیررضا حاتمی', avatar: 'https://i.pravatar.cc/100?img=55', role: 'ریاضی برتر', power: 84, avgScore: 820, accuracy: 84, speed: 7.3 },
      { name: 'مهسا نادری', avatar: 'https://i.pravatar.cc/100?img=37', role: 'تاریخ پژوه', power: 82, avgScore: 808, accuracy: 83, speed: 7.5 },
      { name: 'نیما رجبی', avatar: 'https://i.pravatar.cc/100?img=26', role: 'تحلیل‌گر سریع', power: 81, avgScore: 798, accuracy: 82, speed: 7.7 },
      { name: 'الهه رحیمی', avatar: 'https://i.pravatar.cc/100?img=43', role: 'دانش علوم', power: 80, avgScore: 788, accuracy: 81, speed: 7.9 },
      { name: 'سامیار پاکزاد', avatar: 'https://i.pravatar.cc/100?img=46', role: 'برنامه‌ریز تیمی', power: 78, avgScore: 776, accuracy: 80, speed: 8.1 },
      { name: 'یاسمن گودرزی', avatar: 'https://i.pravatar.cc/100?img=31', role: 'استراتژیست', power: 77, avgScore: 766, accuracy: 79, speed: 8.3 },
      { name: 'هومن جلالی', avatar: 'https://i.pravatar.cc/100?img=51', role: 'دانش عمومی', power: 75, avgScore: 756, accuracy: 78, speed: 8.5 },
      { name: 'بهار قائمی', avatar: 'https://i.pravatar.cc/100?img=35', role: 'مغز خلاق', power: 74, avgScore: 744, accuracy: 77, speed: 8.6 },
    ],
  },
  {
    groupId: 'g5',
    name: 'پیشروان علم',
    score: 21300,
    members: 27,
    admin: 'امیر حسینی',
    created: '۱۴۰۲/۰۲/۲۸',
    wins: 55,
    losses: 16,
    memberList: ['امیر حسینی', 'هانیه ناصری', 'کیارش زندی'],
    matches: [
      { opponentId: 'g1', opponent: 'قهرمانان دانش', time: '۱۴۰۳/۰۶/۰۲ ۲۰:۰۰' },
    ],
    requests: [],
    roster: [
      { name: 'امیر حسینی', avatar: 'https://i.pravatar.cc/100?img=20', role: 'رهبر هوش مصنوعی', power: 93, avgScore: 880, accuracy: 91, speed: 6.2 },
      { name: 'هانیه ناصری', avatar: 'https://i.pravatar.cc/100?img=39', role: 'متخصص زیست', power: 90, avgScore: 868, accuracy: 89, speed: 6.5 },
      { name: 'کیارش زندی', avatar: 'https://i.pravatar.cc/100?img=56', role: 'تحلیل‌گر ریاضی', power: 88, avgScore: 856, accuracy: 88, speed: 6.8 },
      { name: 'محدثه توکلی', avatar: 'https://i.pravatar.cc/100?img=30', role: 'ادبیات پژوه', power: 86, avgScore: 842, accuracy: 87, speed: 7 },
      { name: 'رامین شکیبا', avatar: 'https://i.pravatar.cc/100?img=40', role: 'فیزیک‌دان', power: 85, avgScore: 830, accuracy: 85, speed: 7.2 },
      { name: 'کیانا نعمتی', avatar: 'https://i.pravatar.cc/100?img=60', role: 'متخصص تاریخ', power: 83, avgScore: 818, accuracy: 84, speed: 7.5 },
      { name: 'رامسین اویسی', avatar: 'https://i.pravatar.cc/100?img=15', role: 'کارشناس منطق', power: 82, avgScore: 806, accuracy: 83, speed: 7.7 },
      { name: 'پریسا آذر', avatar: 'https://i.pravatar.cc/100?img=50', role: 'دانش عمومی', power: 80, avgScore: 794, accuracy: 82, speed: 7.9 },
      { name: 'نوید برومند', avatar: 'https://i.pravatar.cc/100?img=16', role: 'تحلیل‌گر داده', power: 78, avgScore: 782, accuracy: 81, speed: 8.1 },
      { name: 'رها صادقی', avatar: 'https://i.pravatar.cc/100?img=11', role: 'حل مسئله سریع', power: 77, avgScore: 770, accuracy: 80, speed: 8.3 },
    ],
  },
];
